[package]
name = "wl-wstp"
version = "0.1.0"
authors = ["Connor Gray <accounts@connorgray.com>"]
edition = "2018"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wl-expr = { git = "ssh://git@stash.wolfram.com:7999/~connorg/wl-expr.git" }
wl-parse = { git = "ssh://git@stash.wolfram.com:7999/~connorg/wl-parse.git" }
wl-wstp-sys = { git = "ssh://git@stash.wolfram.com:7999/~connorg/wl-wstp-sys.git" }